// Hand-curated roster of real historical/modern cricketers.
// Each entry: [id, name, nation, era, role, tier, flavor]
//   tier   — S/A/B/C: overall class at the player's primary skill (batting for
//            batters, bowling for bowlers, both for all-rounders). This stands
//            in for the spec's cohort z-score (§5.1) since no live stats feed
//            this build — it's a hand judgment of "how dominant relative to
//            era peers", which is the same thing the z-score is meant to capture.
//   flavor — H/M/L: for batting roles, strike-rate aggression; for bowling
//            roles, economy/control. Feeds the `strike`/`economy` fields.
//
// Roles: OPEN, TOP, MID, WK, ALL, PACE, SPIN — see server/data/roles.js
// Nations: the 8 wheel segments. Eras: 1970s-2020s.

export const ROSTER = [
  // ---------- INDIA ----------
  ['gavaskar_sunil', 'Sunil Gavaskar', 'India', '1970s', 'OPEN', 'S', 'L'],
  ['sehwag_virender', 'Virender Sehwag', 'India', '2000s', 'OPEN', 'S', 'H'],
  ['rohit_sharma', 'Rohit Sharma', 'India', '2010s', 'OPEN', 'A', 'H'],
  ['dhawan_shikhar', 'Shikhar Dhawan', 'India', '2010s', 'OPEN', 'B', 'M'],
  ['dravid_rahul', 'Rahul Dravid', 'India', '1990s', 'TOP', 'S', 'L'],
  ['pujara_cheteshwar', 'Cheteshwar Pujara', 'India', '2010s', 'TOP', 'B', 'L'],
  ['tendulkar_sachin', 'Sachin Tendulkar', 'India', '1990s', 'MID', 'S', 'M'],
  ['kohli_virat', 'Virat Kohli', 'India', '2010s', 'MID', 'S', 'M'],
  ['azharuddin_mohammad', 'Mohammad Azharuddin', 'India', '1980s', 'MID', 'A', 'M'],
  ['viswanath_gundappa', 'Gundappa Viswanath', 'India', '1970s', 'MID', 'B', 'M'],
  ['dhoni_ms', 'MS Dhoni', 'India', '2000s', 'WK', 'S', 'H'],
  ['engineer_farokh', 'Farokh Engineer', 'India', '1970s', 'WK', 'B', 'M'],
  ['pant_rishabh', 'Rishabh Pant', 'India', '2020s', 'WK', 'A', 'H'],
  ['kapildev', 'Kapil Dev', 'India', '1980s', 'ALL', 'S', 'M'],
  ['jadeja_ravindra', 'Ravindra Jadeja', 'India', '2010s', 'ALL', 'A', 'M'],
  ['pandya_hardik', 'Hardik Pandya', 'India', '2020s', 'ALL', 'B', 'H'],
  ['srinath_javagal', 'Javagal Srinath', 'India', '1990s', 'PACE', 'A', 'M'],
  ['khan_zaheer', 'Zaheer Khan', 'India', '2000s', 'PACE', 'A', 'M'],
  ['bumrah_jasprit', 'Jasprit Bumrah', 'India', '2010s', 'PACE', 'S', 'H'],
  ['shami_mohammed', 'Mohammed Shami', 'India', '2010s', 'PACE', 'A', 'M'],
  ['bedi_bishan', 'Bishan Singh Bedi', 'India', '1970s', 'SPIN', 'A', 'H'],
  ['kumble_anil', 'Anil Kumble', 'India', '1990s', 'SPIN', 'S', 'H'],
  ['ashwin_ravichandran', 'Ravichandran Ashwin', 'India', '2010s', 'SPIN', 'A', 'H'],
  ['prasanna_erapalli', 'Erapalli Prasanna', 'India', '1970s', 'SPIN', 'B', 'M'],

  // ---------- AUSTRALIA ----------
  ['hayden_matthew', 'Matthew Hayden', 'Australia', '2000s', 'OPEN', 'A', 'H'],
  ['warner_david', 'David Warner', 'Australia', '2010s', 'OPEN', 'A', 'H'],
  ['langer_justin', 'Justin Langer', 'Australia', '1990s', 'OPEN', 'B', 'L'],
  ['ponting_ricky', 'Ricky Ponting', 'Australia', '2000s', 'TOP', 'S', 'M'],
  ['smith_steve', 'Steve Smith', 'Australia', '2010s', 'TOP', 'S', 'L'],
  ['border_allan', 'Allan Border', 'Australia', '1980s', 'MID', 'S', 'L'],
  ['clarke_michael', 'Michael Clarke', 'Australia', '2010s', 'MID', 'A', 'M'],
  ['martyn_damien', 'Damien Martyn', 'Australia', '2000s', 'MID', 'B', 'L'],
  ['walters_doug', 'Doug Walters', 'Australia', '1970s', 'MID', 'B', 'M'],
  ['gilchrist_adam', 'Adam Gilchrist', 'Australia', '2000s', 'WK', 'S', 'H'],
  ['healy_ian', 'Ian Healy', 'Australia', '1990s', 'WK', 'B', 'M'],
  ['marsh_rod', 'Rod Marsh', 'Australia', '1970s', 'WK', 'B', 'M'],
  ['watson_shane', 'Shane Watson', 'Australia', '2010s', 'ALL', 'B', 'H'],
  ['symonds_andrew', 'Andrew Symonds', 'Australia', '2000s', 'ALL', 'A', 'H'],
  ['marsh_mitchell', 'Mitchell Marsh', 'Australia', '2020s', 'ALL', 'B', 'M'],
  ['lillee_dennis', 'Dennis Lillee', 'Australia', '1970s', 'PACE', 'S', 'M'],
  ['mcgrath_glenn', 'Glenn McGrath', 'Australia', '1990s', 'PACE', 'S', 'H'],
  ['lee_brett', 'Brett Lee', 'Australia', '2000s', 'PACE', 'A', 'M'],
  ['starc_mitchell', 'Mitchell Starc', 'Australia', '2010s', 'PACE', 'A', 'M'],
  ['thomson_jeff', 'Jeff Thomson', 'Australia', '1970s', 'PACE', 'A', 'L'],
  ['warne_shane', 'Shane Warne', 'Australia', '1990s', 'SPIN', 'S', 'H'],
  ['lyon_nathan', 'Nathan Lyon', 'Australia', '2010s', 'SPIN', 'A', 'H'],

  // ---------- ENGLAND ----------
  ['boycott_geoffrey', 'Geoffrey Boycott', 'England', '1970s', 'OPEN', 'A', 'L'],
  ['gooch_graham', 'Graham Gooch', 'England', '1980s', 'OPEN', 'A', 'M'],
  ['cook_alastair', 'Alastair Cook', 'England', '2010s', 'OPEN', 'A', 'L'],
  ['atherton_michael', 'Michael Atherton', 'England', '1990s', 'TOP', 'B', 'L'],
  ['trott_jonathan', 'Jonathan Trott', 'England', '2010s', 'TOP', 'B', 'L'],
  ['pietersen_kevin', 'Kevin Pietersen', 'England', '2000s', 'MID', 'S', 'H'],
  ['root_joe', 'Joe Root', 'England', '2010s', 'MID', 'S', 'M'],
  ['gower_david', 'David Gower', 'England', '1980s', 'MID', 'A', 'M'],
  ['thorpe_graham', 'Graham Thorpe', 'England', '1990s', 'MID', 'B', 'M'],
  ['knott_alan', 'Alan Knott', 'England', '1970s', 'WK', 'A', 'M'],
  ['prior_matt', 'Matt Prior', 'England', '2000s', 'WK', 'B', 'M'],
  ['buttler_jos', 'Jos Buttler', 'England', '2010s', 'WK', 'A', 'H'],
  ['botham_ian', 'Ian Botham', 'England', '1980s', 'ALL', 'S', 'H'],
  ['flintoff_andrew', 'Andrew Flintoff', 'England', '2000s', 'ALL', 'A', 'H'],
  ['stokes_ben', 'Ben Stokes', 'England', '2010s', 'ALL', 'A', 'H'],
  ['willis_bob', 'Bob Willis', 'England', '1970s', 'PACE', 'A', 'M'],
  ['gough_darren', 'Darren Gough', 'England', '1990s', 'PACE', 'B', 'M'],
  ['anderson_james', 'James Anderson', 'England', '2010s', 'PACE', 'S', 'H'],
  ['broad_stuart', 'Stuart Broad', 'England', '2010s', 'PACE', 'A', 'M'],
  ['underwood_derek', 'Derek Underwood', 'England', '1970s', 'SPIN', 'A', 'H'],
  ['swann_graeme', 'Graeme Swann', 'England', '2010s', 'SPIN', 'A', 'M'],
  ['ali_moeen', 'Moeen Ali', 'England', '2010s', 'SPIN', 'B', 'M'],

  // ---------- WEST INDIES ----------
  ['greenidge_gordon', 'Gordon Greenidge', 'West Indies', '1980s', 'OPEN', 'S', 'M'],
  ['haynes_desmond', 'Desmond Haynes', 'West Indies', '1980s', 'OPEN', 'A', 'M'],
  ['gayle_chris', 'Chris Gayle', 'West Indies', '2000s', 'OPEN', 'S', 'H'],
  ['lara_brian', 'Brian Lara', 'West Indies', '1990s', 'TOP', 'S', 'H'],
  ['kallicharran_alvin', 'Alvin Kallicharran', 'West Indies', '1970s', 'TOP', 'B', 'M'],
  ['richards_viv', 'Viv Richards', 'West Indies', '1970s', 'MID', 'S', 'H'],
  ['lloyd_clive', 'Clive Lloyd', 'West Indies', '1970s', 'MID', 'A', 'M'],
  ['chanderpaul_shivnarine', 'Shivnarine Chanderpaul', 'West Indies', '2000s', 'MID', 'A', 'L'],
  ['pollard_kieron', 'Kieron Pollard', 'West Indies', '2010s', 'MID', 'B', 'H'],
  ['dujon_jeffrey', 'Jeffrey Dujon', 'West Indies', '1980s', 'WK', 'A', 'M'],
  ['ramdin_denesh', 'Denesh Ramdin', 'West Indies', '2010s', 'WK', 'B', 'M'],
  ['sobers_garfield', 'Garfield Sobers', 'West Indies', '1970s', 'ALL', 'S', 'M'],
  ['russell_andre', 'Andre Russell', 'West Indies', '2020s', 'ALL', 'B', 'H'],
  ['holding_michael', 'Michael Holding', 'West Indies', '1980s', 'PACE', 'S', 'M'],
  ['marshall_malcolm', 'Malcolm Marshall', 'West Indies', '1980s', 'PACE', 'S', 'M'],
  ['ambrose_curtly', 'Curtly Ambrose', 'West Indies', '1990s', 'PACE', 'S', 'H'],
  ['walsh_courtney', 'Courtney Walsh', 'West Indies', '1990s', 'PACE', 'A', 'M'],
  ['garner_joel', 'Joel Garner', 'West Indies', '1980s', 'PACE', 'A', 'H'],
  ['gibbs_lance', 'Lance Gibbs', 'West Indies', '1970s', 'SPIN', 'B', 'H'],
  ['narine_sunil', 'Sunil Narine', 'West Indies', '2010s', 'SPIN', 'A', 'H'],

  // ---------- PAKISTAN ----------
  ['anwar_saeed', 'Saeed Anwar', 'Pakistan', '1990s', 'OPEN', 'A', 'H'],
  ['mohsin_khan', 'Mohsin Khan', 'Pakistan', '1980s', 'OPEN', 'B', 'M'],
  ['zaman_fakhar', 'Fakhar Zaman', 'Pakistan', '2010s', 'OPEN', 'B', 'H'],
  ['abbas_zaheer', 'Zaheer Abbas', 'Pakistan', '1980s', 'TOP', 'A', 'M'],
  ['khan_younis', 'Younis Khan', 'Pakistan', '2000s', 'TOP', 'A', 'M'],
  ['miandad_javed', 'Javed Miandad', 'Pakistan', '1980s', 'MID', 'S', 'M'],
  ['inzamam_ul_haq', 'Inzamam-ul-Haq', 'Pakistan', '1990s', 'MID', 'A', 'M'],
  ['azam_babar', 'Babar Azam', 'Pakistan', '2010s', 'MID', 'S', 'M'],
  ['khan_moin', 'Moin Khan', 'Pakistan', '1990s', 'WK', 'B', 'M'],
  ['akmal_kamran', 'Kamran Akmal', 'Pakistan', '2000s', 'WK', 'B', 'M'],
  ['khan_imran', 'Imran Khan', 'Pakistan', '1980s', 'ALL', 'S', 'M'],
  ['afridi_shahid', 'Shahid Afridi', 'Pakistan', '2000s', 'ALL', 'A', 'H'],
  ['razzaq_abdul', 'Abdul Razzaq', 'Pakistan', '2000s', 'ALL', 'B', 'M'],
  ['akram_wasim', 'Wasim Akram', 'Pakistan', '1990s', 'PACE', 'S', 'M'],
  ['younis_waqar', 'Waqar Younis', 'Pakistan', '1990s', 'PACE', 'S', 'M'],
  ['akhtar_shoaib', 'Shoaib Akhtar', 'Pakistan', '2000s', 'PACE', 'A', 'L'],
  ['amir_mohammad', 'Mohammad Amir', 'Pakistan', '2010s', 'PACE', 'B', 'M'],
  ['qadir_abdul', 'Abdul Qadir', 'Pakistan', '1980s', 'SPIN', 'A', 'M'],
  ['mushtaq_saqlain', 'Saqlain Mushtaq', 'Pakistan', '1990s', 'SPIN', 'A', 'H'],
  ['shah_yasir', 'Yasir Shah', 'Pakistan', '2010s', 'SPIN', 'B', 'M'],

  // ---------- SOUTH AFRICA ----------
  ['richards_barry', 'Barry Richards', 'South Africa', '1970s', 'OPEN', 'S', 'H'],
  ['kirsten_gary', 'Gary Kirsten', 'South Africa', '1990s', 'OPEN', 'B', 'L'],
  ['amla_hashim', 'Hashim Amla', 'South Africa', '2010s', 'OPEN', 'A', 'M'],
  ['gibbs_herschelle', 'Herschelle Gibbs', 'South Africa', '2000s', 'TOP', 'A', 'H'],
  ['dussen_rassie', 'Rassie van der Dussen', 'South Africa', '2020s', 'TOP', 'B', 'M'],
  ['devilliers_ab', 'AB de Villiers', 'South Africa', '2010s', 'MID', 'S', 'H'],
  ['duplessis_faf', 'Faf du Plessis', 'South Africa', '2010s', 'MID', 'A', 'M'],
  ['boucher_mark', 'Mark Boucher', 'South Africa', '2000s', 'WK', 'B', 'M'],
  ['dekock_quinton', 'Quinton de Kock', 'South Africa', '2010s', 'WK', 'A', 'H'],
  ['procter_mike', 'Mike Procter', 'South Africa', '1970s', 'ALL', 'A', 'M'],
  ['kallis_jacques', 'Jacques Kallis', 'South Africa', '2000s', 'ALL', 'S', 'M'],
  ['donald_allan', 'Allan Donald', 'South Africa', '1990s', 'PACE', 'S', 'M'],
  ['pollock_shaun', 'Shaun Pollock', 'South Africa', '2000s', 'PACE', 'A', 'H'],
  ['steyn_dale', 'Dale Steyn', 'South Africa', '2010s', 'PACE', 'S', 'M'],
  ['rabada_kagiso', 'Kagiso Rabada', 'South Africa', '2020s', 'PACE', 'A', 'M'],
  ['tahir_imran', 'Imran Tahir', 'South Africa', '2010s', 'SPIN', 'B', 'M'],
  ['adams_paul', 'Paul Adams', 'South Africa', '1990s', 'SPIN', 'B', 'M'],

  // ---------- SRI LANKA ----------
  ['jayasuriya_sanath', 'Sanath Jayasuriya', 'Sri Lanka', '1990s', 'OPEN', 'S', 'H'],
  ['tharanga_upul', 'Upul Tharanga', 'Sri Lanka', '2010s', 'OPEN', 'B', 'M'],
  ['dilshan_tillakaratne', 'Tillakaratne Dilshan', 'Sri Lanka', '2000s', 'OPEN', 'A', 'H'],
  ['desilva_aravinda', 'Aravinda de Silva', 'Sri Lanka', '1990s', 'TOP', 'A', 'H'],
  ['gurusinha_asanka', 'Asanka Gurusinha', 'Sri Lanka', '1990s', 'TOP', 'B', 'M'],
  ['jayawardene_mahela', 'Mahela Jayawardene', 'Sri Lanka', '2000s', 'MID', 'S', 'M'],
  ['mathews_angelo', 'Angelo Mathews', 'Sri Lanka', '2010s', 'MID', 'B', 'M'],
  ['ranatunga_arjuna', 'Arjuna Ranatunga', 'Sri Lanka', '1990s', 'MID', 'B', 'M'],
  ['sangakkara_kumar', 'Kumar Sangakkara', 'Sri Lanka', '2000s', 'WK', 'S', 'M'],
  ['kaluwitharana_romesh', 'Romesh Kaluwitharana', 'Sri Lanka', '1990s', 'WK', 'B', 'H'],
  ['perera_thisara', 'Thisara Perera', 'Sri Lanka', '2010s', 'ALL', 'B', 'H'],
  ['hasaranga_wanindu', 'Wanindu Hasaranga', 'Sri Lanka', '2020s', 'ALL', 'A', 'M'],
  ['vaas_chaminda', 'Chaminda Vaas', 'Sri Lanka', '2000s', 'PACE', 'A', 'H'],
  ['malinga_lasith', 'Lasith Malinga', 'Sri Lanka', '2010s', 'PACE', 'A', 'M'],
  ['kulasekara_nuwan', 'Nuwan Kulasekara', 'Sri Lanka', '2010s', 'PACE', 'B', 'M'],
  ['muralitharan_muttiah', 'Muttiah Muralitharan', 'Sri Lanka', '2000s', 'SPIN', 'S', 'H'],
  ['herath_rangana', 'Rangana Herath', 'Sri Lanka', '2010s', 'SPIN', 'A', 'M'],

  // ---------- NEW ZEALAND ----------
  ['turner_glenn', 'Glenn Turner', 'New Zealand', '1970s', 'OPEN', 'A', 'L'],
  ['wright_john', 'John Wright', 'New Zealand', '1980s', 'OPEN', 'B', 'L'],
  ['guptill_martin', 'Martin Guptill', 'New Zealand', '2010s', 'OPEN', 'B', 'H'],
  ['williamson_kane', 'Kane Williamson', 'New Zealand', '2010s', 'TOP', 'S', 'M'],
  ['congdon_bevan', 'Bevan Congdon', 'New Zealand', '1970s', 'TOP', 'B', 'L'],
  ['taylor_ross', 'Ross Taylor', 'New Zealand', '2010s', 'MID', 'A', 'M'],
  ['crowe_martin', 'Martin Crowe', 'New Zealand', '1980s', 'MID', 'S', 'M'],
  ['mccullum_brendon', 'Brendon McCullum', 'New Zealand', '2000s', 'WK', 'A', 'H'],
  ['watling_bj', 'BJ Watling', 'New Zealand', '2010s', 'WK', 'B', 'L'],
  ['cairns_chris', 'Chris Cairns', 'New Zealand', '1990s', 'ALL', 'A', 'H'],
  ['neesham_jimmy', 'Jimmy Neesham', 'New Zealand', '2010s', 'ALL', 'B', 'M'],
  ['hadlee_richard', 'Richard Hadlee', 'New Zealand', '1980s', 'PACE', 'S', 'M'],
  ['bond_shane', 'Shane Bond', 'New Zealand', '2000s', 'PACE', 'A', 'M'],
  ['boult_trent', 'Trent Boult', 'New Zealand', '2010s', 'PACE', 'A', 'M'],
  ['southee_tim', 'Tim Southee', 'New Zealand', '2010s', 'PACE', 'B', 'M'],
  ['vettori_daniel', 'Daniel Vettori', 'New Zealand', '2000s', 'SPIN', 'A', 'H'],
  ['sodhi_ish', 'Ish Sodhi', 'New Zealand', '2010s', 'SPIN', 'B', 'M'],
];
